name: anomaly-detection-atlas-env
dependencies:
- python=2.7.14
- pip=9.0.1
- pytz=2018.4
- python-dateutil=2.6
- numpy=1.14
- pandas=0.22
- statsmodels=0.8
- scikit-learn=0.19.1
- ipython=5.4.1
- pip:
    - influxdb==5.0.0
    - tzlocal==1.5.1